name: Build Windows EXE
on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install pyinstaller pandas openpyxl pillow matplotlib xlrd
    - run: pyinstaller --onefile --windowed --name "Excel_Karsilastirma_CAL" main.py
    - uses: actions/upload-artifact@v3
      with:
        name: Excel_Karsilastirma_EXE
        path: dist/Excel_Karsilastirma_CAL.exe
