name: Build and Release

on:
  push:
    tags:
      - 'v*'  # v1.0.0, v2.0.0 gibi taglerde tetiklenir

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE
        run: pyinstaller --onefile --windowed --name Excel_Karsilastirma_CAL main.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Excel_Karsilastirma_CAL.exe
          tag_name: ${{ github.ref_name }}  # Otomatik tag kullanımı
          name: "Release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}